import { Book, Review, Category } from '../types';

export const categories: Category[] = [
  { id: '1', name: 'Prayer Books', slug: 'prayer-books', count: 24 },
  { id: '2', name: 'Liturgical Books', slug: 'liturgical', count: 18 },
  { id: '3', name: 'Lives of Saints', slug: 'saints', count: 32 },
  { id: '4', name: 'Theology & Doctrine', slug: 'theology', count: 28 },
  { id: '5', name: 'Church History', slug: 'history', count: 15 },
  { id: '6', name: 'Icons & Art', slug: 'icons', count: 12 },
  { id: '7', name: "Children's Books", slug: 'children', count: 20 },
  { id: '8', name: 'Music & CDs', slug: 'music', count: 8 },
];

export const books: Book[] = [
  {
    id: '1',
    title: 'The Orthodox Prayer Book',
    author: 'Holy Trinity Monastery',
    price: 25.00,
    originalPrice: 30.00,
    rating: 4.9,
    reviewCount: 128,
    coverImage: '/images/products/2013/09/20060122prayerbook1.jpg',
    category: 'Prayer Books',
    publisher: 'St. Tikhon\'s Seminary Press',
    year: 2020,
    pages: 420,
    description: 'A comprehensive collection of Orthodox prayers for daily use, including morning and evening prayers, prayers before and after Holy Communion, and prayers for various needs. This beautifully bound edition features clear typography and durable construction.',
    inStock: true,
    isNew: true,
    isBestseller: true,
  },
  {
    id: '2',
    title: 'The Divine Liturgy of St. John Chrysostom',
    author: 'St. John Chrysostom',
    price: 18.50,
    rating: 4.8,
    reviewCount: 95,
    coverImage: '/images/products/2013/10/cabasilasliturgy.jpg',
    category: 'Liturgical Books',
    publisher: 'Orthodox Bookstore',
    year: 2019,
    pages: 180,
    description: 'The complete text of the Divine Liturgy with commentary and explanations. Includes the full service in English with rubrics and instructions for the faithful.',
    inStock: true,
    isBestseller: true,
  },
  {
    id: '3',
    title: 'The Life of St. Sergius of Radonezh',
    author: 'Archpriest Victor Potapov',
    price: 22.00,
    rating: 4.7,
    reviewCount: 67,
    coverImage: '/images/products/2014/06/sergiy.jpg',
    category: 'Lives of Saints',
    publisher: 'Printshop of St. Job of Pochaev',
    year: 2021,
    pages: 280,
    description: 'A detailed account of the life of St. Sergius, the wonderworker of Radonezh, one of Russia\'s most beloved saints. This biography explores his spiritual journey and the founding of the Holy Trinity-St. Sergius Lavra.',
    inStock: true,
  },
  {
    id: '4',
    title: 'Orthodox Dogmatic Theology',
    author: 'Protopresbyter Michael Pomazansky',
    price: 35.00,
    originalPrice: 42.00,
    rating: 4.9,
    reviewCount: 156,
    coverImage: '/images/products/2014/07/pravoslavie.jpg',
    category: 'Theology & Doctrine',
    publisher: 'St. Herman of Alaska Brotherhood',
    year: 2018,
    pages: 380,
    description: 'A comprehensive introduction to Orthodox theology covering all major dogmas and doctrines of the Church. Written with clarity and precision, this text is suitable for both beginners and advanced students.',
    inStock: true,
    isBestseller: true,
  },
  {
    id: '5',
    title: 'The Veneration of the Theotokos',
    author: 'Archimandrite Epiphanius',
    price: 19.99,
    rating: 4.6,
    reviewCount: 43,
    coverImage: '/images/products/2013/10/venerationtheotokos.jpg',
    category: 'Theology & Doctrine',
    publisher: 'Holy Dormition Monastery',
    year: 2020,
    pages: 220,
    description: 'An exploration of the Orthodox understanding of the Virgin Mary, her role in salvation history, and the proper veneration due to her as the Mother of God.',
    inStock: true,
  },
  {
    id: '6',
    title: 'The Truth of Our Faith',
    author: 'Elder Cleopa of Romania',
    price: 28.00,
    rating: 4.8,
    reviewCount: 89,
    coverImage: '/images/products/2013/10/truthandcommunion.jpg',
    category: 'Theology & Doctrine',
    publisher: 'Uncut Mountain Press',
    year: 2017,
    pages: 340,
    description: 'A classic work of Orthodox spiritual instruction covering fundamental topics of faith, prayer, and the spiritual life. Elder Cleopa\'s wisdom shines through in these accessible teachings.',
    inStock: true,
  },
  {
    id: '7',
    title: 'The Mystery of Faith',
    author: 'Hieromonk Gregorios',
    price: 24.50,
    rating: 4.7,
    reviewCount: 52,
    coverImage: '/images/products/2015/03/mystery1.jpg',
    category: 'Theology & Doctrine',
    publisher: 'Orthodox Witness',
    year: 2022,
    pages: 290,
    description: 'An introduction to the Orthodox understanding of the sacraments and the life of grace in the Church. Explores the mystical dimension of Orthodox worship.',
    inStock: true,
    isNew: true,
  },
  {
    id: '8',
    title: 'The Great Canon of St. Andrew',
    author: 'St. Andrew of Crete',
    price: 15.00,
    rating: 4.9,
    reviewCount: 78,
    coverImage: '/images/products/2016/04/EasterKanon.jpg',
    category: 'Liturgical Books',
    publisher: 'St. Tikhon\'s Seminary Press',
    year: 2019,
    pages: 120,
    description: 'The complete text of the Great Canon with commentary. This penitential hymn is sung during Great Lent and is one of the masterpieces of Orthodox hymnography.',
    inStock: true,
  },
  {
    id: '9',
    title: 'The Faith of the Saints',
    author: 'Archbishop Averky',
    price: 21.00,
    rating: 4.8,
    reviewCount: 64,
    coverImage: '/images/products/2013/11/faithofsaints.jpg',
    category: 'Theology & Doctrine',
    publisher: 'Holy Trinity Monastery',
    year: 2018,
    pages: 260,
    description: 'A collection of patristic teachings on the fundamental truths of Orthodox Christianity. An excellent resource for catechism and personal study.',
    inStock: true,
  },
  {
    id: '10',
    title: 'The Optina Elders',
    author: 'Ivan Kontzevitch',
    price: 32.00,
    originalPrice: 38.00,
    rating: 4.9,
    reviewCount: 112,
    coverImage: '/images/products/2016/01/Zhitia_optin1.jpg',
    category: 'Lives of Saints',
    publisher: 'St. Herman of Alaska Brotherhood',
    year: 2021,
    pages: 450,
    description: 'The lives and teachings of the renowned Optina Elders, the last great spiritual fathers of Russia before the revolution. Their wisdom continues to guide Orthodox Christians worldwide.',
    inStock: true,
    isBestseller: true,
  },
  {
    id: '11',
    title: 'The Liturgy of the Hours',
    author: 'Monk Moses',
    price: 27.00,
    rating: 4.6,
    reviewCount: 38,
    coverImage: '/images/products/2016/03/HOURS_Cover.jpg',
    category: 'Liturgical Books',
    publisher: 'Ancient Faith Publishing',
    year: 2020,
    pages: 310,
    description: 'A guide to the daily cycle of Orthodox prayer services. Includes the text of the Hours with explanations and practical guidance for lay participation.',
    inStock: true,
  },
  {
    id: '12',
    title: 'The Meaning of Icons',
    author: 'Leonid Ouspensky',
    price: 45.00,
    rating: 4.9,
    reviewCount: 143,
    coverImage: '/images/products/2014/02/Du.jpg',
    category: 'Icons & Art',
    publisher: 'St. Vladimir\'s Seminary Press',
    year: 2016,
    pages: 420,
    description: 'The definitive work on the theology and spirituality of Orthodox iconography. Explores the meaning, technique, and spiritual significance of sacred images.',
    inStock: true,
    isBestseller: true,
  },
  {
    id: '13',
    title: 'The First Steps in Church Life',
    author: 'Priest Daniel Sysoev',
    price: 16.00,
    rating: 4.7,
    reviewCount: 91,
    coverImage: '/images/products/2016/04/katechisis.jpg',
    category: "Children's Books",
    publisher: 'Orthodox Missionary School',
    year: 2022,
    pages: 150,
    description: 'An introduction to Orthodox Christianity for children and young people. Covers basic prayers, church etiquette, and the fundamentals of the faith.',
    inStock: true,
    isNew: true,
  },
  {
    id: '14',
    title: 'The Holy Trinity',
    author: 'St. Basil the Great',
    price: 19.50,
    rating: 4.8,
    reviewCount: 56,
    coverImage: '/images/products/2014/07/troica.jpg',
    category: 'Theology & Doctrine',
    publisher: 'Catholic University of America Press',
    year: 2019,
    pages: 200,
    description: 'St. Basil\'s classic treatise on the Holy Trinity, foundational for Orthodox Trinitarian theology. Includes the famous discussion of the divinity of the Holy Spirit.',
    inStock: true,
  },
  {
    id: '15',
    title: 'The Life of St. Nektarios',
    author: 'Sotos Chondropoulos',
    price: 26.00,
    rating: 4.8,
    reviewCount: 87,
    coverImage: '/images/products/2015/10/nektarios1.jpg',
    category: 'Lives of Saints',
    publisher: 'Holy Trinity Monastery',
    year: 2021,
    pages: 320,
    description: 'The inspiring life of St. Nektarios of Aegina, one of the most beloved saints of modern times. From humble beginnings to becoming a bishop and wonderworker.',
    inStock: true,
  },
  {
    id: '16',
    title: 'The Typica Service',
    author: 'Archimandrite Ephraim',
    price: 14.00,
    rating: 4.5,
    reviewCount: 29,
    coverImage: '/images/products/2015/07/typica1.jpg',
    category: 'Liturgical Books',
    publisher: 'St. Anthony\'s Greek Orthodox Monastery',
    year: 2018,
    pages: 100,
    description: 'The service of Typica for use when a priest is not available. Includes the full text with instructions for lay readers.',
    inStock: true,
  },
  {
    id: '17',
    title: 'The History of the Russian Church',
    author: 'Metropolitan Makary',
    price: 38.00,
    originalPrice: 45.00,
    rating: 4.7,
    reviewCount: 72,
    coverImage: '/images/products/2014/11/hist_cover1.jpg',
    category: 'Church History',
    publisher: 'Printshop of St. Job of Pochaev',
    year: 2017,
    pages: 580,
    description: 'A comprehensive history of the Russian Orthodox Church from its baptism in 988 to the 19th century. Based on extensive archival research.',
    inStock: true,
  },
  {
    id: '18',
    title: 'The Sacrament of Marriage',
    author: 'Archpriest John Meyendorff',
    price: 20.00,
    rating: 4.6,
    reviewCount: 45,
    coverImage: '/images/products/2014/11/marriage.jpg',
    category: 'Theology & Doctrine',
    publisher: 'St. Vladimir\'s Seminary Press',
    year: 2020,
    pages: 180,
    description: 'An exploration of the Orthodox understanding of marriage as a sacrament and path to salvation. Includes practical guidance for Christian spouses.',
    inStock: true,
  },
  {
    id: '19',
    title: 'The Passion Week Services',
    author: 'Holy Trinity Monastery',
    price: 30.00,
    rating: 4.9,
    reviewCount: 98,
    coverImage: '/images/products/2015/05/passion1.jpg',
    category: 'Liturgical Books',
    publisher: 'Holy Trinity Monastery',
    year: 2022,
    pages: 380,
    description: 'The complete services of Holy Week in English, including all the hymns, readings, and prayers. An essential resource for Holy Week participation.',
    inStock: true,
    isNew: true,
    isBestseller: true,
  },
  {
    id: '20',
    title: 'The Vespers Service',
    author: 'Archimandrite Ephraim',
    price: 18.00,
    rating: 4.7,
    reviewCount: 53,
    coverImage: '/images/products/2015/09/vespers1.jpg',
    category: 'Liturgical Books',
    publisher: 'St. Anthony\'s Greek Orthodox Monastery',
    year: 2019,
    pages: 160,
    description: 'The full text of the Vespers service with commentary. Explains the structure and meaning of this foundational daily service.',
    inStock: true,
  },
];

export const reviews: Review[] = [
  {
    id: '1',
    author: 'Maria Johnson',
    rating: 5,
    date: '2024-01-15',
    text: 'This prayer book has been a blessing to my daily spiritual life. The translations are beautiful and the binding is durable. Highly recommended!',
  },
  {
    id: '2',
    author: 'Michael Chen',
    rating: 5,
    date: '2024-01-10',
    text: 'Excellent resource for understanding Orthodox theology. Clear, comprehensive, and faithful to the tradition.',
  },
  {
    id: '3',
    author: 'Elizabeth Davis',
    rating: 4,
    date: '2024-01-05',
    text: 'Beautiful book with insightful commentary. The only reason for 4 stars is that I wish it had more illustrations.',
  },
  {
    id: '4',
    author: 'David Petrov',
    rating: 5,
    date: '2023-12-28',
    text: 'A treasure for anyone interested in the lives of the saints. The writing is engaging and spiritually nourishing.',
  },
  {
    id: '5',
    author: 'Anna Smith',
    rating: 5,
    date: '2023-12-20',
    text: 'Purchased this for my godchild and they love it. Perfect introduction to the faith for young people.',
  },
];

export function getBookById(id: string): Book | undefined {
  return books.find(book => book.id === id);
}

export function getBooksByCategory(categorySlug: string): Book[] {
  const category = categories.find(c => c.slug === categorySlug);
  if (!category) return [];
  return books.filter(book => book.category === category.name);
}

export function getNewArrivals(): Book[] {
  return books.filter(book => book.isNew).slice(0, 6);
}

export function getBestsellers(): Book[] {
  return books.filter(book => book.isBestseller).slice(0, 6);
}

export function getRelatedBooks(bookId: string): Book[] {
  const book = getBookById(bookId);
  if (!book) return [];
  return books
    .filter(b => b.category === book.category && b.id !== bookId)
    .slice(0, 4);
}
